const FRAME_STYLES = {
  classic: {
    id: 'classic',
    name: 'Klasik',
    desc: '4 baris vertikal, border putih bersih',
    bg: '#F8F9F6',
    border: '#C5D0B8',
    accent: '#9CAF88',
    text: '#2D3A2D',
    watermark: 'Photobooth.',
    previewBg: 'bg-white',
    previewBorder: 'border-sage-200',
    slotBg: 'bg-sage-100',
    slotBorder: 'border-sage-200',
    label: 'text-sage-400',
    cameraBorder: 'border-sage-300/40',
  },
  polaroid: {
    id: 'polaroid',
    name: 'Polaroid',
    desc: 'Bingkai putih tebal dengan bayangan retro',
    bg: '#FAFAFA',
    border: '#D4D4D4',
    accent: '#A3A3A3',
    text: '#404040',
    watermark: 'Photobooth.',
    previewBg: 'bg-white',
    previewBorder: 'border-gray-200',
    slotBg: 'bg-gray-100',
    slotBorder: 'border-gray-200',
    label: 'text-gray-400',
    cameraBorder: 'border-gray-300/40',
  },
  vintage: {
    id: 'vintage',
    name: 'Vintage',
    desc: 'Border krem dengan sudut ornamental',
    bg: '#FDF8F0',
    border: '#E8D5B0',
    accent: '#C4A97D',
    text: '#5C4A2A',
    watermark: 'Photobooth.',
    previewBg: 'bg-amber-50',
    previewBorder: 'border-amber-200',
    slotBg: 'bg-amber-100/60',
    slotBorder: 'border-amber-200',
    label: 'text-amber-400',
    cameraBorder: 'border-amber-300/40',
  },
  modern: {
    id: 'modern',
    name: 'Modern Minimal',
    desc: 'Garis tipis, spasio rapi, tanpa border',
    bg: '#F8F9F6',
    border: '#DDE2D8',
    accent: '#9CAF88',
    text: '#2D3A2D',
    watermark: 'Photobooth.',
    previewBg: 'bg-sage-50',
    previewBorder: 'border-transparent',
    slotBg: 'bg-sage-100',
    slotBorder: 'border-sage-200',
    label: 'text-sage-400',
    cameraBorder: 'border-sage-300/30',
  },
  botanical: {
    id: 'botanical',
    name: 'Botanical',
    desc: 'Border dedaunan sage dengan aksen gold',
    bg: '#F0F7F0',
    border: '#A8C5A0',
    accent: '#B8944E',
    text: '#2D4A2D',
    watermark: 'Botanical.',
    previewBg: 'bg-emerald-50',
    previewBorder: 'border-emerald-200',
    slotBg: 'bg-emerald-100/60',
    slotBorder: 'border-emerald-200',
    label: 'text-emerald-400',
    cameraBorder: 'border-emerald-300/40',
  },
  'double-border': {
    id: 'double-border',
    name: 'Double Frame',
    desc: 'Garis bingkai ganda ala studio lawas',
    bg: '#F5F0EB',
    border: '#C4B8A8',
    accent: '#8C7A64',
    text: '#3D3228',
    watermark: 'Photobooth.',
    previewBg: 'bg-stone-50',
    previewBorder: 'border-stone-300',
    slotBg: 'bg-stone-100',
    slotBorder: 'border-stone-300',
    label: 'text-stone-400',
    cameraBorder: 'border-stone-300/40',
  },
  'cutie-cat': {
    id: 'cutie-cat',
    name: 'Cutie Cat',
    desc: 'Pink gemas dengan motif kuping kucing',
    bg: '#FFF0F3',
    border: '#FFB3C1',
    accent: '#FF6394',
    text: '#590D22',
    watermark: 'Meow!',
    previewBg: 'bg-pink-50',
    previewBorder: 'border-pink-200',
    slotBg: 'bg-pink-100/60',
    slotBorder: 'border-pink-200',
    label: 'text-pink-400',
    cameraBorder: 'border-pink-300/40',
  },
  'retro-pop': {
    id: 'retro-pop',
    name: 'Retro Pop',
    desc: 'Warna-warni neon penuh semangat',
    bg: '#FFFBE6',
    border: '#FFD60A',
    accent: '#FF6B6B',
    text: '#1A1A2E',
    watermark: 'Pop!',
    previewBg: 'bg-yellow-50',
    previewBorder: 'border-yellow-200',
    slotBg: 'bg-yellow-100/60',
    slotBorder: 'border-yellow-200',
    label: 'text-yellow-500',
    cameraBorder: 'border-yellow-300/40',
  },
};

export default FRAME_STYLES;

export function getFrameStyle(templateId) {
  return FRAME_STYLES[templateId] || FRAME_STYLES.classic;
}
